//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BirFikrimVar.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PostResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PostResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BirFikrimVar.Resources.PostResources", typeof(PostResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change your account settings.
        /// </summary>
        public static string AccountSettingsTitle {
            get {
                return ResourceManager.GetString("AccountSettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a phone number.
        /// </summary>
        public static string AddPhoneNumber {
            get {
                return ResourceManager.GetString("AddPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Posts.
        /// </summary>
        public static string AdminPostsTitle {
            get {
                return ResourceManager.GetString("AdminPostsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to this article.
        /// </summary>
        public static string Article {
            get {
                return ResourceManager.GetString("Article", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link your {0} account.
        /// </summary>
        public static string AssociateProvider {
            get {
                return ResourceManager.GetString("AssociateProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link Form.
        /// </summary>
        public static string AssociationForm {
            get {
                return ResourceManager.GetString("AssociationForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in using your {0} account
        ///.
        /// </summary>
        public static string ButtonTitle {
            get {
                return ResourceManager.GetString("ButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to by.
        /// </summary>
        public static string By {
            get {
                return ResourceManager.GetString("By", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change password.
        /// </summary>
        public static string ChangePasswordButton {
            get {
                return ResourceManager.GetString("ChangePasswordButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password Form.
        /// </summary>
        public static string ChangePasswordForm {
            get {
                return ResourceManager.GetString("ChangePasswordForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        public static string ChangePasswordTitle {
            get {
                return ResourceManager.GetString("ChangePasswordTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change your password.
        /// </summary>
        public static string ChangeYourPassword {
            get {
                return ResourceManager.GetString("ChangeYourPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code .
        /// </summary>
        public static string Code_ {
            get {
                return ResourceManager.GetString("Code_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Comment.
        /// </summary>
        public static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment Message.
        /// </summary>
        public static string CommentMessage {
            get {
                return ResourceManager.GetString("CommentMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your comment has been sent successfully.
        /// </summary>
        public static string CommentSent {
            get {
                return ResourceManager.GetString("CommentSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment Text.
        /// </summary>
        public static string CommentText {
            get {
                return ResourceManager.GetString("CommentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Email.
        /// </summary>
        public static string ConfirmEmail {
            get {
                return ResourceManager.GetString("ConfirmEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm new password.
        /// </summary>
        public static string ConfirmNewPassword {
            get {
                return ResourceManager.GetString("ConfirmNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new account.
        /// </summary>
        public static string CreateAccountHeading {
            get {
                return ResourceManager.GetString("CreateAccountHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create .
        /// </summary>
        public static string CreateAction {
            get {
                return ResourceManager.GetString("CreateAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Local Login.
        /// </summary>
        public static string CreateLocalLogin {
            get {
                return ResourceManager.GetString("CreateLocalLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Password.
        /// </summary>
        public static string CreatePasswordTitle {
            get {
                return ResourceManager.GetString("CreatePasswordTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new post.
        /// </summary>
        public static string CreatePost {
            get {
                return ResourceManager.GetString("CreatePost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current password.
        /// </summary>
        public static string CurrentPassword {
            get {
                return ResourceManager.GetString("CurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post Date.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The post has been unsaved successfully.
        /// </summary>
        public static string DeletePostMessage {
            get {
                return ResourceManager.GetString("DeletePostMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for confirming your email. Please.
        /// </summary>
        public static string EmailThanks {
            get {
                return ResourceManager.GetString("EmailThanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Enter verification code.
        /// </summary>
        public static string EnterVerificationCode {
            get {
                return ResourceManager.GetString("EnterVerificationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signed in with {0}. Enter your email and press Register.
        /// </summary>
        public static string ExternalAuthInfo {
            get {
                return ResourceManager.GetString("ExternalAuthInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to :External Logins.
        /// </summary>
        public static string ExternalLoginsLabel {
            get {
                return ResourceManager.GetString("ExternalLoginsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check your email to reset your password..
        /// </summary>
        public static string ForgotPasswordCheckEmail {
            get {
                return ResourceManager.GetString("ForgotPasswordCheckEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot Password Confirmation.
        /// </summary>
        public static string ForgotPasswordConfirmTitle {
            get {
                return ResourceManager.GetString("ForgotPasswordConfirmTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your email.
        /// </summary>
        public static string ForgotPasswordEnterEmail {
            get {
                return ResourceManager.GetString("ForgotPasswordEnterEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ?Forgot your password.
        /// </summary>
        public static string ForgotPasswordTitle {
            get {
                return ResourceManager.GetString("ForgotPasswordTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        public static string Image {
            get {
                return ResourceManager.GetString("Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Like.
        /// </summary>
        public static string Like {
            get {
                return ResourceManager.GetString("Like", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Like has been added successfully.
        /// </summary>
        public static string LikeAdded {
            get {
                return ResourceManager.GetString("LikeAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liked.
        /// </summary>
        public static string Liked {
            get {
                return ResourceManager.GetString("Liked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Like has been Removed.
        /// </summary>
        public static string LikeRemoved {
            get {
                return ResourceManager.GetString("LikeRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use a local account to log in.
        /// </summary>
        public static string LocalLoginHeading {
            get {
                return ResourceManager.GetString("LocalLoginHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsuccessful login with service.
        /// </summary>
        public static string LoginFailureMsg {
            get {
                return ResourceManager.GetString("LoginFailureMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Login Failure.
        /// </summary>
        public static string LoginFailureTitle {
            get {
                return ResourceManager.GetString("LoginFailureTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to click here to log in.
        /// </summary>
        public static string LoginHere {
            get {
                return ResourceManager.GetString("LoginHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in .
        /// </summary>
        public static string LoginTitle {
            get {
                return ResourceManager.GetString("LoginTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to Log in.
        /// </summary>
        public static string LogLink {
            get {
                return ResourceManager.GetString("LogLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage .
        /// </summary>
        public static string ManageAction {
            get {
                return ResourceManager.GetString("ManageAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage your external logins.
        /// </summary>
        public static string ManageExternalLoginsTitle {
            get {
                return ResourceManager.GetString("ManageExternalLoginsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage.
        /// </summary>
        public static string ManageTitle {
            get {
                return ResourceManager.GetString("ManageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password.
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Likers Yet.
        /// </summary>
        public static string NoLikersYet {
            get {
                return ResourceManager.GetString("NoLikersYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have a local username/password for this site. Add a local account so you can log in without an external login.
        /// </summary>
        public static string NoLocalAccountInfo {
            get {
                return ResourceManager.GetString("NoLocalAccountInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no external authentication services configured. See.
        /// </summary>
        public static string NonCon1 {
            get {
                return ResourceManager.GetString("NonCon1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to for details on setting up this ASP.NET application to support logging in via external services.
        /// </summary>
        public static string NonCon2 {
            get {
                return ResourceManager.GetString("NonCon2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to :Password.
        /// </summary>
        public static string PasswordLabel {
            get {
                return ResourceManager.GetString("PasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your phone number.
        /// </summary>
        public static string PhoneNumberPlaceholder {
            get {
                return ResourceManager.GetString("PhoneNumberPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        public static string PhoneNumberTitle {
            get {
                return ResourceManager.GetString("PhoneNumberTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post.
        /// </summary>
        public static string Post {
            get {
                return ResourceManager.GetString("Post", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post submitted — pending approval
        ///.
        /// </summary>
        public static string PostAddedMessage {
            get {
                return ResourceManager.GetString("PostAddedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post Plot.
        /// </summary>
        public static string PostPlot {
            get {
                return ResourceManager.GetString("PostPlot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post has been published successfully.
        /// </summary>
        public static string PostPublishMessage {
            get {
                return ResourceManager.GetString("PostPublishMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The post has been rejected successfully.
        /// </summary>
        public static string PostRejectMessage {
            get {
                return ResourceManager.GetString("PostRejectMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The post has been saved successfully.
        /// </summary>
        public static string PostSavedMessage {
            get {
                return ResourceManager.GetString("PostSavedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish.
        /// </summary>
        public static string Publish {
            get {
                return ResourceManager.GetString("Publish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read.
        /// </summary>
        public static string Read {
            get {
                return ResourceManager.GetString("Read", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string RegisterBtn {
            get {
                return ResourceManager.GetString("RegisterBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registered Logins.
        /// </summary>
        public static string RegisteredLogins {
            get {
                return ResourceManager.GetString("RegisteredLogins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register as a new user.
        /// </summary>
        public static string RegisterNewUser {
            get {
                return ResourceManager.GetString("RegisterNewUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string RegisterTitle {
            get {
                return ResourceManager.GetString("RegisterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reject.
        /// </summary>
        public static string Reject {
            get {
                return ResourceManager.GetString("Reject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember this browser.
        /// </summary>
        public static string RememberBrowser {
            get {
                return ResourceManager.GetString("RememberBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember me.
        /// </summary>
        public static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove this {0} login from your account.
        /// </summary>
        public static string RemoveThisLoginTitle {
            get {
                return ResourceManager.GetString("RemoveThisLoginTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset .
        /// </summary>
        public static string ResetBtn {
            get {
                return ResourceManager.GetString("ResetBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset password confirmation.
        /// </summary>
        public static string ResetPasswordConfirmTitle {
            get {
                return ResourceManager.GetString("ResetPasswordConfirmTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password has been reset. Please.
        /// </summary>
        public static string ResetPasswordDone {
            get {
                return ResourceManager.GetString("ResetPasswordDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset your password.
        /// </summary>
        public static string ResetPasswordHeading {
            get {
                return ResourceManager.GetString("ResetPasswordHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset password.
        /// </summary>
        public static string ResetPasswordTitle {
            get {
                return ResourceManager.GetString("ResetPasswordTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved.
        /// </summary>
        public static string Saved {
            get {
                return ResourceManager.GetString("Saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved Posts.
        /// </summary>
        public static string SavedPosts {
            get {
                return ResourceManager.GetString("SavedPosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save for later.
        /// </summary>
        public static string SaveForLater {
            get {
                return ResourceManager.GetString("SaveForLater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Results for.
        /// </summary>
        public static string SearchResultLabel {
            get {
                return ResourceManager.GetString("SearchResultLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to : Select Two-Factor Authentication Provider.
        /// </summary>
        public static string Select2FAProvider {
            get {
                return ResourceManager.GetString("Select2FAProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string SendCodeTitle {
            get {
                return ResourceManager.GetString("SendCodeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Link.
        /// </summary>
        public static string SendResetLink {
            get {
                return ResourceManager.GetString("SendResetLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send verification code.
        /// </summary>
        public static string SendVerificationCode {
            get {
                return ResourceManager.GetString("SendVerificationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set password.
        /// </summary>
        public static string SetPasswordButton {
            get {
                return ResourceManager.GetString("SetPasswordButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Comments.
        /// </summary>
        public static string ShowComments {
            get {
                return ResourceManager.GetString("ShowComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Likers.
        /// </summary>
        public static string ShowLikers {
            get {
                return ResourceManager.GetString("ShowLikers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort.
        /// </summary>
        public static string Sort {
            get {
                return ResourceManager.GetString("Sort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags.
        /// </summary>
        public static string Tags {
            get {
                return ResourceManager.GetString("Tags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        public static string Text {
            get {
                return ResourceManager.GetString("Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no two-factor authentication providers configured. See.
        /// </summary>
        public static string TwoFactorNone1 {
            get {
                return ResourceManager.GetString("TwoFactorNone1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to for details on setting up this ASP.NET application to support two-factor authentication.
        /// </summary>
        public static string TwoFactorNone2 {
            get {
                return ResourceManager.GetString("TwoFactorNone2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to :Two-Factor Authentication.
        /// </summary>
        public static string TwoFactorTitle {
            get {
                return ResourceManager.GetString("TwoFactorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use another service to log in.
        /// </summary>
        public static string UseAnthor {
            get {
                return ResourceManager.GetString("UseAnthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify Phone Number.
        /// </summary>
        public static string VerifyPhoneNumberTitle {
            get {
                return ResourceManager.GetString("VerifyPhoneNumberTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify .
        /// </summary>
        public static string VerifyTitle {
            get {
                return ResourceManager.GetString("VerifyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string WriterName {
            get {
                return ResourceManager.GetString("WriterName", resourceCulture);
            }
        }
    }
}
